# Generated by Django 3.2.7 on 2021-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.CharField(default=4500, max_length=250),
            preserve_default=False,
        ),
    ]
