# Generated by Django 3.2.7 on 2021-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_registration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hp',
            field=models.CharField(default=45, max_length=250),
            preserve_default=False,
        ),
    ]
