# Generated by Django 3.2.7 on 2021-12-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_registration_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='hp',
            new_name='typ',
        ),
    ]
