# Generated by Django 3.2.7 on 2021-12-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_hp_registration_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='img',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
