# Generated by Django 3.2.7 on 2021-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_registration_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
