# Generated by Django 3.2.7 on 2021-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_registration_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
