# Generated by Django 3.2.7 on 2021-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_registration_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
