# Generated by Django 3.2.7 on 2021-12-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_registration_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registration'},
        ),
    ]
