# Generated by Django 3.2.7 on 2021-12-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_registration_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='img',
        ),
    ]
