# Generated by Django 3.2.7 on 2021-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_registration_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='img',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
